### ISSUE TITLE
解决修改物编数据后优化空地图会导致数据剧烈爆炸的问题

### ISSUE THREAD

**Issue by LazyKnightX** [XYWE/XYWE#11]
经过 地图优化精灵 1.87 对原版YDWE 1.30.6的空图(删除了农民的最后一个技能，删除了所有触发目录，自定义脚本区增加一个“//”用于切换版本到w3x)进行优化测试后，体积从16kb变为255kb。

需要解决这个优化BUG。

据反馈使用1.27的YDWE的全UI保存不会出现这问题。

**Comment by LazyKnightX** [comment]
初步对比MPQ后发现经过YDWE打开并保存后的地图的War3mapMap.blp与保存前的原图的War3mapMap.blp的内部数据不同，怀疑是blp相关计算工具出现异常。

**Comment by luciouskami** [comment]
唔 ydwe保存以后可能会把作者之前设置的小地图直接替换成地形的预览图

**Comment by LazyKnightX** [comment]
有相关代码路径么，我提取MPQ验证后，把这个blp复制到正常的地图里就爆炸了额

**Comment by luciouskami** [comment]
他的blp转换库有问题。代码目前处于不可读状态。

**Comment by LazyKnightX** [comment]
好的，Issue我去提交好了，直接告诉他步骤

**Comment by LazyKnightX** [comment]
已提交Issue：https://github.com/actboy168/YDWE/issues/71

会继续跟进后续

**Comment by LazyKnightX** [comment]
ab已拒绝该Issue，后续由我们自行处理

**Comment by LazyKnightX** [comment]
1.30.3 ~ 1.30.4 ~ 1.30.4 Patch
2016-10-12 19:16:59 ~ 2016-11-06 16:04:11 ~ 2016-11-06 19:43:08

BUG在1.30.3~1.30.4之间

**Comment by LazyKnightX** [comment]
怀疑为移除了YDGraph导致的错误

**Comment by LazyKnightX** [comment]
相关Issue：https://github.com/XYWE/XYWE/issues/14

**Comment by LazyKnightX** [comment]
已修复，原因为YDWE后续更新中替换了SFMpq，将其改为动态编译导致头信息不断变更致使使用老版本SFMpq的工具由于SFMpq自带的验证机制而无法正常读取war3mapMap.blp数据从而产生崩溃/数据异常处理。
